on:
  push:
    branches:
      - main

env:
  MONGO_VERSION: "5.0.15"
  BUILDER_VERSION: "5-amd64"

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Run MongoDB build"
        run: |
          mkdir -p ./buildoutput
          docker run --rm -v ${PWD}/buildoutput:/buildoutput groundhog2k/mongo-builder:$BUILDER_VERSION /bin/bash "-c" "./build.sh $MONGO_VERSION"
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Login to the container registry"
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: "Build and push"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: groundhog2k/mongo:${{ env.MONGO_VERSION }}
          build-args: |
            MONGO_VERSION=${{ env.MONGO_VERSION }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
