on: [pull_request]

env:
  MONGO_VERSION: "5.0.15"

jobs:
  verify:
    name: "Verify the build process"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Run build simulation"
        run: |
          mkdir -p ./buildoutput
          touch ./buildoutput/test
      - name: "Verify that container image can be build"
        run: docker build . -t grounhog2k/mongo:verify --build-arg MONGO_VERSION=$MONGO_VERSION"
