on: [pull_request]

env:
  MONGO_VERSION: "6.0.5"
  BUILDER_VERSION: "5-amd64"

jobs:
  verify:
    name: "Verify the build process"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Run build simulation"
        run: |
          mkdir -p ./buildoutput
          # docker run --rm -v ${PWD}/buildoutput:/buildoutput groundhog2k/mongo-builder:$BUILDER_VERSION /bin/bash "-c" "./build.sh $MONGO_VERSION"
          touch ./buildoutput/test
      - name: "Verify that container image can be build"
        run: docker build . -t groundhog2k/mongo:verify-$MONGO_VERSION --build-arg MONGO_VERSION=$MONGO_VERSION
